#!/bin/sh

if [ "$DEBUG" ]; then
    DEBUGOPT='-g -O0'
fi

case "$1" in
    main)
        gcc $DEBUGOPT -o fm cl_getc.c util.c parser.c stack.c dict.c eval.c && ./fm
        ;;
    eval-test)
        gcc $DEBUGOPT -DEVAL_TEST -g -O0 -o eval-test cl_getc.c util.c parser.c stack.c dict.c eval.c && ./eval-test
        ;;
    dict-test)
        gcc $DEBUGOPT -DDICT_TEST -g -O0 -o dict-test cl_getc.c util.c parser.c stack.c dict.c && ./dict-test
        ;;
    stack-test)
        gcc $DEBUGOPT -DSTACK_TEST -o stack-test cl_getc.c util.c parser.c stack.c && ./stack-test
        ;;
    parser-test)
        gcc $DEBUGOPT -DPARSER_TEST -o parser-test cl_getc.c util.c parser.c && ./parser-test
        ;;
esac
