#!/bin/sh

case "$1" in
    main)
        gcc -o fm cl_getc.c util.c parser.c stack.c dict.c eval.c && ./fm
        ;;
    dict-test)
        gcc -DDICT_TEST -o dict-test cl_getc.c util.c parser.c stack.c dict.c && ./dict-test
        ;;
    stack-test)
        gcc -DSTACK_TEST -o stack-test cl_getc.c util.c parser.c stack.c && ./stack-test
        ;;
    parser-test)
        gcc -DPARSER_TEST -o parser-test cl_getc.c util.c parser.c && ./parser-test
        ;;
esac
